### ISSUE TITLE
SSH Uri and private key

### ISSUE THREAD

**Issue by studeni** [swisscom/gitlab-merge-request-resource#17]
Username and password works just fine but using SSH fails with the following exception:

resource script '/opt/resource/check []' failed: exit status 3

Thank you

**Comment by mastertinner** [comment]
@studeni, can you please check if this got resolved by 7bcab70bd863db924b5b107ff109a001c194d5a5?

**Comment by studeni** [comment]
@mastertinner I still see the same issue using mastertinner/gitlab-merge-request-resource as a docker image. Did you only update the github repo but not the docker?
Thank you
Nik

**Comment by mastertinner** [comment]
@studeni, yes the Docker image should be up to date. Can you post your configuration?
